language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database unicore_ask_test;' -U postgres
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - find ./unicore/ask -name '*.py' -not -path '*/alembic/*' | xargs pep8
  - find ./unicore/ask -name '*.py' -not -path '*/alembic/*' | xargs pyflakes
  - ./run_tests.sh
after_success:
  - coveralls

